development:
    adapter: sqlite3
    database: db/development.db
    pool: 5
    timeout: 5000

production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: <%= ENV['QOVERY_DATABASE_INDIO_HOST'] %>
    database: <%= ENV['QOVERY_DATABASE_INDIO_NAME'] %>
    username: <%= ENV['QOVERY_DATABASE_INDIO_USERNAME'] %>
    password: <%= ENV['QOVERY_DATABASE_INDIO_PASSWORD'] %>